source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PlayerView_Example', :exclusive => true do
  pod 'PlayerView', :path => '../'
end

target 'PlayerView_Tests', :exclusive => true do
  pod 'PlayerView', :path => '../'

  
end
